packages:
  - "apps/*"
  - "packages/*"
  - "e2e"
allowBuilds:
  "@embedded-postgres/linux-x64": true
  "@embedded-postgres/windows-x64": true
  "@prisma/engines": true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
